{{- if and .Values.istio .Values.istio.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: corveil
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "corveil.labels" . | nindent 4 }}
    app.kubernetes.io/part-of: corveil
    app.kubernetes.io/component: corveil
spec:
  gateways:
  {{- range .Values.istio.corveil.gateways }}
    - {{ . }}
  {{- end }}
  hosts:
  {{- range .Values.istio.corveil.hosts }}
    - {{ tpl . $ }}
  {{- end }}
  http:
    - route:
        - destination:
            port:
              number: {{ .Values.service.port }}
            host: {{ include "corveil.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
{{- end }}
